lib/pkgcloud/openstack/storage/file.js

Directories now have names and a content type of 'application/directory'.

Improved directory support for Openstack getFiles

---

lib/pkgcloud/openstack/client.js
lib/pkgcloud/openstack/context/identity.js

When trying to authenticate against an Openstack server with a self-signed certificate, I kept running into 
[Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE] even though I had set the strictSSL flag to false on the config option.
After debugging, it turns out we weren't passing in the strictSSL option down to the authorize method in the Openstack identity type. This PR changes the getIdentityOptions to pass in the flag and also the authorize function to use the flag.

Allow non strict ssl in Openstack provider

---

README.md
lib/pkgcloud/amazon/client.js
lib/pkgcloud/core/base/client.js
test/common/base/client-test.js
test/common/base/useragent-test.js

- part of #394
- This only affects all clients the derive from core/base/client.js
- This is probably 95% of all network traffic
- There are some one-offs that need broader investigation on the correct strategy

Add support for prepending a custom user agent

---

lib/pkgcloud/google/storage/client/files.js

Fixes #400 
This was a fail. gcloud updates the original `file` instance with new metadata after a successful operation. I should have passed the original file reference to `new storage.File`, not the argument to `complete`.

storage: google: upload: return metadata in success handler - fixes #400

---

package.json

fix "memory usage bug when downloading objects from Amazon S3" motivated by email from Amazon:
> Dear Amazon Web Services Customer,
> 
> Our logs indicate that your account has used or is using a version of the AWS SDK for JavaScript that  is affected by a memory usage bug when downloading objects from Amazon S3. The affected versions are 2.1.13, 2.1.14, and 2.1.15.
> 
> The latest 2.1.16 version of the SDK includes the related fix, and it is critical that you upgrade to the latest version to avoid being affected by it.

[dist] upgrade aws-sdk dependency to 2.1.17

---

lib/pkgcloud/openstack/client.js
lib/pkgcloud/openstack/storage/client/files.js

1. Add `abort` on `openstack`'s client.download
1. `openstack`'s file request should able to add header such as `Range`
1. give `response` and `error` event to callback
close #379 also

Cancel openstack's client.download

---

lib/pkgcloud/amazon/compute/client/servers.js

amazon createServer: use pluralized keys for SecurityGroups/SecurityGroupIds

---

lib/pkgcloud/common/auth.js

This makes all tests pass on iojs.
https://github.com/iojs/io.js/commit/979d0ca874df0383311ca06f154f6965074
196ee introduced throwing an error when the header value is undefined.

auth: only set x-auth-project-id header if truthy

---

docs/providers/amazon.md

Typical AWS examples and even the AWS interfaces that output access keys output the access key id first, then the secret key.
This makes the examples confusing and likely someone will insert the wrong value for the wrong key.

Flip the keyId and key in Amazon examples

---

lib/pkgcloud/openstack/database/client/instances.js
test/common/databases/instances-test.js

When calling `typeof` on an array, `object` is returned. So creating a database instance and including the database names in the `databases` property will fail.
Ex.
```
> var a = []
undefined
> typeof a
'object'
> Array.isArray(a)
true
> typeof a === 'array'
false
```

[database]: use Array.isArray instead of typeof

---

docs/providers/rackspace/databases.md
lib/pkgcloud/openstack/database/client/instances.js
test/common/databases/instances-test.js

Adds enableRootUser and listRootStatus for rackspace cloud databases.
I understand if this PR exposes more functionality that wanted being as it allows enabling the root user for rackspace databases. Although, it is something that I have actually needed before. If the tests are not up to snuff, I can add more.

[database]: Add enableRootUser and listRootStatus

---

lib/pkgcloud/openstack/client.js
lib/pkgcloud/openstack/context/identity.js
lib/pkgcloud/openstack/context/service.js

OpenStack updated Keystone to V3 and it contains a number of changes that should be addressed via pkgcloud.
http://docs.openstack.org/developer/keystone/http-api.html
client.js
- A goal is to maintain backwards compatibility with v2.
- keystoneAuthVersion is used to default to v2 if a version is not specified
identity.js
- The new path for obtaining the token is v3/auth/tokens instead of v2.0/tokens.
- Authentication in v3 now happens against domains
- The token is returned in the x-subject-token header
service.js
- In V3 the format was changed for how endpoints and interfaces are used. On returning endpoints, an object is created for each interface type now.

OpenStack Keystone/Identity V3 Updates

---

lib/pkgcloud/openstack/compute/client/extensions/security-group-rules.js

Issue #453 described that
openstack/compute/client/extensions/security-group-rules.js lacked the
deleteRule method.

Added deleteRule

---

lib/pkgcloud/openstack/network/client/securityGroups.js

Issue #454. The typo caused the response from openstack to createSecurityGroup not to be passed on to the user.

Fix typo in createSecurityGroup

---

lib/pkgcloud/openstack/network/client/securityGroupRules.js

Issue #556.
In lib/pkgcloud/openstack/network/client/securityGroupRules.js the createSecurityGroupRule code uses 'body.securityGroupRule' in the callback, this should be 'body.security_group_rule' ( line 111 ).
The respose from openstack is documented [here](http://developer.openstack.org/api-ref/networking/v2/?expanded=create-security-group-rule-detail#create-security-group-rule).

Fix typo in openstack createSecurityGroupRule

---

lib/pkgcloud/openstack/storage/client/account.js
lib/pkgcloud/openstack/storage/client/index.js
lib/pkgcloud/openstack/storage/storageClient.js
test/openstack/storage/temp-url-test.js

This pull requests adds temporary url functionality to openstack storage.  It is modeled off of the code written specifically for the rackspace provider as well as the similar implementation from [pyrax](https://github.com/rackspace/pyrax).
With this update, you can both set and get the temporary url key associated with your account in addition to generating the temporary url itself.
Because the rackspace storage provider uses the openstack provider's storageClient object, it was necessary to add the additional file file `account.js` along with the corresponding extend in `client/index.js`.
There were no previous tests written for openstack storage so I have created a few simple ones for this new functionality.  Due to my unfamiliarity with `hock` they may be more verbose than is needed …

[storage] Add temporary url functionality to openstack storage

---

docs/providers/google.md
lib/pkgcloud/google/storage/client/files.js

Content-Type will always be text/plain, which causes issues when trying to open the file if it isn't plaintext (such as a pdf). 
This fixes that by either looking up the mime type, or using the provided contentType.
Addresses Issue [634](https://github.com/pkgcloud/pkgcloud/issues/634)

Set Content-Type with google storage

---

lib/pkgcloud/amazon/storage/client/containers.js
lib/pkgcloud/google/storage/client/containers.js
lib/pkgcloud/openstack/context/identity.js
lib/pkgcloud/openstack/context/service.js
lib/pkgcloud/openstack/database/client/users.js
test/common/base/client-test.js
test/common/databases/flavor-test.js
test/hp/storage/file-test.js

Fix jshint errors et failing unit test.
```javascript
./node_modules/.bin/jshint --exclude-path .gitignore .
lib/pkgcloud/amazon/storage/client/containers.js: line 131, col 12, 'deleteFiles' was used before it was defined.
lib/pkgcloud/amazon/storage/client/containers.js: line 135, col 12, 'destroyFile' was used before it was defined.
lib/pkgcloud/google/storage/client/containers.js: line 112, col 12, 'deleteFiles' was used before it was defined.
lib/pkgcloud/google/storage/client/containers.js: line 116, col 12, 'destroyFile' was used before it was defined.
lib/pkgcloud/openstack/context/identity.js: line 195, col 12, 'getTenantId' was used before it was defined.
lib/pkgcloud/openstack/context/service.js: line 114, col 12, 'getUrl' was used before it was defined. …
```

Fix build (jshint + unit test)

---

CHANGELOG.md
docs/providers/amazon.md
lib/pkgcloud/amazon/storage/client/files.js
lib/pkgcloud/amazon/storage/client/index.js
package.json
test/common/storage/base-test.js
test/common/storage/upload-test.js

* Update the aws-sdk
* Use `upload` method of native `aws-sdk` rather than external `s3-upload-stream` module
* expose concurrency - `queueSize` and `partSize` configurability for the `client.upload` method
* expose `managedUpload` object on returned stream which provides ability to abort upload or track upload progress
* Fixed download/upload tests for large files which have been  skipped till now.
Due to `aws-sdk`'s weird design, extra processing steps had to be added to preserve `client.upload` method behavior. (I refer to two proxy streams used in the `upload` method). 
Certainly not good solution... however it seems there is no better one. 
Some download/upload test tweaks had to be made due to behavior of `aws-sdk`'s `upload` method which makes one `putObject` request if an object …

Amazon storage use native aws-sdk for uploads

---

lib/pkgcloud/azure/storage/client/index.js

Issue 526 Fixed
* this.protocol from client instance is used as the URL protocol as it should be
* That value can be set in "options" when the azure client is set (i.e. using loopback-component-storage just write "protocol": "https://" or "http://" and for other uses, is the analog. By default is "https://")
* The change is in just one line, no depth change was needed

Issue 526 Fixed

---

lib/pkgcloud/google/storage/client/files.js

The `storage.upload()` for provider `google` fails with a `FILE_NO_UPLOAD` error:
```
{ Error: The uploaded data did not match the data from the server. As a precaution, the file has been deleted. To be sure the content is the same, you should try uploading the file again.
[...]
code: 'FILE_NO_UPLOAD',
}
```
This is because the `writableStream.on('data',` listener snatches data away from being passed to GCS. In my testings only 3 to 10 % of a ~300KB file reached the bucket. The `@google-cloud/storage` library throws the `FILE_NO_UPLOAD` error while checking the hash of the uploaded file against the hash of its fraction in GCS. Which is correct as contents do not match.
Removing the `.on('data'` listener fixed this issue. I think this emit is not really needed as the `proxyStream` of the …

Fix GCS upload
